window.SB_EXAM = {
  title: "L’épreuve régionale",
  titleAr: "الامتحان الجهوي",
  kicker: "25 % du bac · 1er Bac SM et EX",
  kickerAr: "25٪ من الباك · أولى باك علوم رياضية وتجريبية",
  lead:
    "Les cours du site couvrent le cadre. Cette page dit comment on te note : structure du sujet, barème, ordre des questions, piège classique. Ce n’est pas une copie d’annale officielle — c’est le plan type du CNE, pour t’entraîner sans voler un PDF.",
  leadAr:
    "دروس الموقع تغطّي الإطار المرجعي. هذه الصفحة تشرح كيف تُنقَّط: بنية الموضوع، السّلم، ترتيب الأسئلة، والفخ المعتاد. ليست نسخة من امتحان رسمي، بل الخطاطة المعتمدة عند المركز الوطني للامتحانات، لتتدرّب دون سرقة ملف PDF.",
  drill:
    "Toutes les deux semaines : 1 production française ou 1 paragraphe HG + 1 situation d’islam (Yusuf). Le jour J, tu ne découvres pas le barème.",
  drillAr:
    "كل أسبوعين: إنتاج كتابي بالفرنسية أو فقرة في الاجتماعيات + وضعية في التربية الإسلامية (يوسف). يوم الامتحان لا تكتشف السّلم لأوّل مرة.",
  ui: {
    fr: {
      order: "Dans l’ordre, le jour J",
      trap: "Piège",
      hurry: "Si tu es pressé",
      courses: "Cours du site pour cette épreuve",
      points: "points",
      session: "Session",
      subjects: "Matière de l’épreuve",
      unavailable: "Épreuve indisponible.",
    },
    ar: {
      order: "الترتيب يوم الامتحان",
      trap: "الفخ",
      hurry: "إذا كنت مستعجلاً",
      courses: "دروس الموقع لهذه المادة",
      points: "نقطة",
      session: "الدورة",
      subjects: "مادة الامتحان",
      unavailable: "صفحة الامتحان غير متاحة.",
    },
  },
  papers: [
    {
      id: "ar",
      subject: "ar",
      name: "Arabe",
      nameAr: "العربية",
      nameLong: "اللغة العربية",
      badge: "ar",
      total: 20,
      parts: [
        {
          title: "النصوص",
          points: 10,
          what: "Texte (مقالة، شعر، قصة) : compréhension, procédés, valeur. Preuves dans le texte, pas une bio du poète.",
          whatAr: "نص (مقالة، شعر، قصة): فهم، أساليب، قيمة. الشواهد من النص، لا سيرة الشاعر.",
        },
        {
          title: "علوم اللغة",
          points: 4,
          what: "Application directe : مصادر، نسبة، تمييز، عدد، أمر/نهي، استفهام/تمني. Le وزن et le tableau battent l’intuition.",
          whatAr: "تطبيق مباشر: مصادر، نسبة، تمييز، عدد، أمر/نهي، استفهام/تمنّي. الوزن والجدول أقوى من الحدس.",
        },
        {
          title: "تعبير وإنشاء",
          points: 6,
          what: "Une compétence : توسيع فكرة، تحليل صورة، ou الربط بين الأفكار. Cohérence > volume.",
          whatAr: "مهارة واحدة: توسيع فكرة، أو تحليل صورة، أو الربط بين الأفكار. الانسجام أهم من الحجم.",
        },
      ],
      method: [
        "Lis le texte une fois pour la thèse / le conflit, une fois pour les procédés.",
        "Langue : fais le tableau au brouillon (وزن، نوع، إعراب) avant d’écrire la phrase.",
        "Expression : reformule la consigne, puis 1 idée par phrase de lien.",
        "Relis : accords, hamza, et que tu as bien fait la compétence demandée — pas une autre.",
      ],
      methodAr: [
        "اقرأ النص مرّة للأطروحة أو الصراع، ومرّة للأساليب.",
        "اللغة: ارسم الجدول في المسودة (وزن، نوع، إعراب) قبل كتابة الجملة.",
        "التعبير: أعد صياغة المطلوب، ثم فكرة واحدة في كل جملة ربط.",
        "راجع: المطابقة، الهمزة، وأنك أجبت المهارة المطلوبة لا مهارة أخرى.",
      ],
      trap: "Raconter le texte comme une histoire, ou coller un plan tout fait sans mots du document.",
      trapAr: "سرد النص كقصة، أو لصق تصميم جاهز دون ألفاظ الوثيقة.",
      hurry: "Thèse en une phrase + 2 procédés + 1 exercice de langue + 8 lignes d’expression avec 2 outils de lien.",
      hurryAr: "الأطروحة في جملة + أسلوبان + تمرين لغوي + ثمانية أسطر تعبير برابطين.",
      paper: {
        title: "Sujet type (sciences)",
        titleAr: "موضوع نموذجي (الشعب العلمية)",
        time: "Gère 2 h : 50 min texte, 20 min langue, 40 min expression, 10 min relecture.",
        timeAr: "وزّع ساعتين: 50 د للنص، 20 د للغة، 40 د للتعبير، 10 د للمراجعة.",
        steps: [
          "Document : article d’idées (تنمية، تسامح) ou poème d’إحياء / سؤال الذات, ou nouvelle courte.",
          "Questions : idée générale, parties, champ lexical, image, valeur.",
          "Langue : 2 items du cadre (ex. nombre + tamyīz, ou amr + maṣdar).",
          "Expression : توسيع d’une phrase du texte, ou analyse d’une image liée au thème.",
        ],
        stepsAr: [
          "الوثيقة: مقالة أفكار (تنمية، تسامح) أو قصيدة إحياء / سؤال الذات، أو قصة قصيرة.",
          "الأسئلة: الفكرة العامة، الأجزاء، الحقل المعجمي، الصورة، القيمة.",
          "اللغة: عنصران من الإطار (مثلاً العدد والتمييز، أو الأمر والمصدر).",
          "التعبير: توسيع جملة من النص، أو تحليل صورة مرتبطة بالموضوع.",
        ],
      },
      courses: ["maqala", "shir-ihya", "masadir", "tamyiz", "adad", "tawsi-fikra", "tahlil-sura", "rabt-afkar"],
    },
    {
      id: "fr",
      subject: "fr",
      name: "Français",
      nameAr: "الفرنسية",
      nameLong: "Langue française",
      nameLongAr: "اللغة الفرنسية",
      badge: "fr",
      total: 20,
      parts: [
        {
          title: "Étude de texte",
          titleAr: "دراسة النص",
          points: 10,
          what: "Extrait d’une des trois œuvres. Situation, compréhension, champ lexical, figures, point de vue.",
          whatAr: "مقتطف من أحد المؤلفات الثلاثة. الوضعية، الفهم، الحقل المعجمي، الصور البلاغية، وجهة النظر.",
        },
        {
          title: "Production écrite",
          titleAr: "الإنتاج الكتابي",
          points: 10,
          what: "Lettre, essai ou dialogue. Sujet, destinataire, thèse, plan, langue et ponctuation.",
          whatAr: "رسالة أو مقال أو حوار. الموضوع، المرسل إليه، الأطروحة، التصميم، اللغة والترقيم.",
        },
      ],
      method: [
        "Situe l’extrait (œuvre, moment, qui parle) en 3 lignes avant les questions.",
        "Pour une figure : nomme, cite, dis l’effet (ironie, pathétique, accusation).",
        "Production : 5 min de plan au brouillon. Intro courte, 2 arguments, conclusion.",
        "Dernières 5 min : accords, homophones, tu/vous selon le destinataire.",
      ],
      methodAr: [
        "حدّد المقتطف (المؤلف، اللحظة، من يتكلم) في ثلاثة أسطر قبل الأسئلة.",
        "للصورة البلاغية: سمّها، استشهد، بيّن الأثر (سخرية، شفقة، اتهام).",
        "الإنتاج: خمس دقائق تصميماً في المسودة. مقدمة قصيرة، حجتان، خاتمة.",
        "آخر خمس دقائق: المطابقة، المتجانسات، tu/vous حسب المرسل إليه.",
      ],
      trap: "Résumer toute l’œuvre, ou une intro de quinze lignes et un développement vide.",
      trapAr: "تلخيص المؤلف كله، أو مقدمة من خمسة عشر سطراً وتطوير فارغ.",
      hurry: "3 indices d’énonciation + 2 figures + production en 3 paragraphes égaux.",
      hurryAr: "ثلاث قرائن تلفظ + صورتان + إنتاج في ثلاث فقرات متوازنة.",
      paper: {
        title: "Sujet type (toutes filières)",
        titleAr: "موضوع نموذجي (جميع الشعب)",
        time: "Gère 2 h : 55 min texte, 55 min production, 10 min relecture.",
        timeAr: "وزّع ساعتين: 55 د للنص، 55 د للإنتاج، 10 د للمراجعة.",
        steps: [
          "Texte : Boîte à merveilles (enfance, portrait), Antigone (réplique Créon–Antigone), ou Dernier Jour (peur, thèse contre la peine).",
          "Questions : locuteur, champ lexical, 2 figures, avis justifié.",
          "Production : même thème que l’extrait (lettre au directeur, essai « faut-il obéir à la loi ? », etc.).",
          "Respecte le type demandé : une lettre n’est pas un essai.",
        ],
        stepsAr: [
          "النص: علبة العجائب (طفولة، بورتريه)، أنتيغون (مواجهة كريون وأنتيغون)، أو اليوم الأخير (خوف، أطروحة ضد الإعدام).",
          "الأسئلة: المتكلم، الحقل المعجمي، صورتان، رأي معلَّل.",
          "الإنتاج: الموضوع نفسه (رسالة للمدير، مقال «هل تجب طاعة القانون؟»).",
          "احترم النوع المطلوب: الرسالة ليست مقالاً.",
        ],
      },
      courses: ["boite-merveilles", "antigone", "dernier-jour", "figures-style", "enonciation", "types-arguments", "production-ecrite"],
    },
    {
      id: "islam",
      subject: "islam",
      name: "Éduc. islamique",
      nameAr: "التربية الإسلامية",
      nameLong: "التربية الإسلامية",
      badge: "islam",
      total: 20,
      parts: [
        {
          title: "الوضعية",
          points: 8,
          what: "Lis la situation, formule l’إشكال, dis les attitudes des parties.",
          whatAr: "اقرأ الوضعية، صغ الإشكال، بيّن مواقف الأطراف.",
        },
        {
          title: "التعليل والاستدلال",
          points: 8,
          what: "Justifie avec le cours (تعريف، حكم، مقاصد) et une āya de Yusuf du cadre.",
          whatAr: "علّل بمكتسب الدرس (تعريف، حكم، مقاصد) وبآية من سورة يوسف في الإطار.",
        },
        {
          title: "القيم والموقف",
          points: 4,
          what: "Valeur + comportement concret. Pas un sermon.",
          whatAr: "قيمة + سلوك ملموس. ليست موعظة.",
        },
      ],
      method: [
        "Souligne dans la situation : qui, quel conflit, quel مدخل (عقيدة، أسرة، قسط…).",
        "Écris l’إشكال en une question, pas un paragraphe.",
        "Chaque idée : notion du cadre + āya Yusuf (pas une autre sourate au hasard).",
        "Ferme par un acte (école, famille, argent, environnement).",
      ],
      methodAr: [
        "خطّ في الوضعية: من؟ أي صراع؟ أي مدخل (عقيدة، أسرة، قسط…)؟",
        "اكتب الإشكال سؤالاً واحداً، لا فقرة.",
        "كل فكرة: مفهوم من الإطار + آية يوسف (لا سورة أخرى عشوائياً).",
        "اختم بعمل (مدرسة، أسرة، مال، بيئة).",
      ],
      trap: "Raconter Yusuf comme un film, ou coller une āya hors sujet.",
      trapAr: "سرد يوسف كفيلم، أو لصق آية خارج الموضوع.",
      hurry: "إشكال + 2 attitudes + 1 تعريف + 1 āya + 1 acte.",
      hurryAr: "إشكال + موقفان + تعريف + آية + عمل.",
      paper: {
        title: "Sujet type (toutes filières)",
        titleAr: "موضوع نموذجي (جميع الشعب)",
        time: "Gère 1 h : 10 min lecture, 40 min rédaction, 10 min versets.",
        timeAr: "وزّع ساعة: 10 د قراءة، 40 د تحرير، 10 د للآيات.",
        steps: [
          "Situation : deux élèves, un mariage, un dépôt d’argent, un gaspillage d’eau, une tentation — un conflit lisible.",
          "Questions types : حدد الإشكال / بين الموقف / علل / استدل من سورة يوسف / اقترح سلوكاً.",
          "Tu n’as pas à tout le programme : 1 leçon du مدخل + Yusuf suffisent si c’est juste.",
          "Apprends 8 à 10 āyas du cadre (صبر، عفة، أمانة، تمكين، عفو), pas les 111 versets par cœur.",
        ],
        stepsAr: [
          "الوضعية: تلميذان، زواج، وديعة مال، هدر ماء، فتنة — صراع واضح.",
          "أسئلة نمطية: حدد الإشكال / بيّن الموقف / علّل / استدل من سورة يوسف / اقترح سلوكاً.",
          "لا تحتاج المقرر كله: درس واحد من المدخل + يوسف يكفي إن كان دقيقاً.",
          "احفظ 8 إلى 10 آيات من الإطار (صبر، عفة، أمانة، تمكين، عفو)، لا المئة والأحد عشر آية عن ظهر قلب.",
        ],
      },
      courses: ["surat-yusuf", "iman-ghayb", "zawaj", "haqq-nafs-sabr", "haqq-ghayr-iffa", "kafa-istikhqa"],
    },
    {
      id: "hg",
      subject: "hg",
      name: "اجتماعيات",
      nameAr: "الاجتماعيات",
      nameLong: "Histoire-Géographie",
      nameLongAr: "التاريخ والجغرافيا",
      badge: "hg",
      total: 20,
      parts: [
        {
          title: "Article (au choix)",
          titleAr: "المقال (اختياري)",
          points: 10,
          what: "Un sujet d’histoire ou de géo parmi deux. Méthode 2 pts, fond 7, forme 1.",
          whatAr: "موضوع تاريخ أو جغرافيا من اثنين. المنهج 2 ن، المعرفة 7، الشكل 1.",
        },
        {
          title: "Documents (l’autre matière)",
          titleAr: "الاشتغال بالوثائق (المادة الأخرى)",
          points: 10,
          what: "Si tu rédiges l’histoire, tu travailles les docs de géo — et l’inverse. Pas les deux articles.",
          whatAr: "إن كتبت مقال التاريخ تشتغل وثائق الجغرافيا — والعكس. لا مقالين معاً.",
        },
      ],
      method: [
        "Choisis l’article sur la matière où tu as le plus de faits, pas « celle qui a l’air facile ».",
        "Intro : temps, lieu, enjeu, 2 questions. Corps : 2 ou 3 parties. Conclusion : bilan + ouverture.",
        "Docs : type, date, auteur, puis extraire, relier, commenter — pas recopier le document.",
        "Géo : toujours مظهر → عامل → تدخل / حد. Histoire : causes → faits → effets.",
      ],
      methodAr: [
        "اختر المقال في المادة التي تملك فيها وقائع أكثر، لا «الأسهل مظهراً».",
        "المقدمة: زمن، مكان، رهان، سؤالان. العرض: جزءان أو ثلاثة. الخاتمة: حصيلة وانفتاح.",
        "الوثائق: النوع، التاريخ، صاحبها، ثم استخراج وربط وتعليق — لا نسخ الوثيقة.",
        "الجغرافيا دائماً: مظهر → عامل → تدخل / حد. التاريخ: أسباب → وقائع → نتائج.",
      ],
      trap: "Une liste de dates sans phrase, ou coller WWII dans le sujet 1929.",
      trapAr: "لائحة تواريخ بلا جملة، أو لصق الحرب الثانية في موضوع 1929.",
      hurry: "Intro de 4 lignes + 2 parties de 8 lignes + 1 carte mentale (Atlas, littoral, ou alliances 1914).",
      hurryAr: "مقدمة من أربعة أسطر + جزءان من ثمانية + خريطة ذهنية (الأطلس، الساحل، أو أحلاف 1914).",
      paper: {
        title: "Sujet type (SM / EX)",
        titleAr: "موضوع نموذجي (علوم رياضية / تجريبية)",
        time: "Gère 2 h : 10 min choix, 50 min article, 50 min docs, 10 min forme.",
        timeAr: "وزّع ساعتين: 10 د للاختيار، 50 د للمقال، 50 د للوثائق، 10 د للشكل.",
        steps: [
          "Article hist possible : transformations du XIXe, impérialisme et 1914, nahḍa, pressions sur le Maroc, 1918–1929, WWII, ḥimāya, indépendance.",
          "Article géo possible : développement, ressources du Maroc, aménagement, eau/désert, USA, UE, Chine.",
          "Docs : textes, carte, tableau, courbe — définir 2 termes, extraire 3 faits, une phrase de synthèse.",
          "En géo, un schéma (Nord/Sud, ou axes du Maroc) remplace souvent un roman.",
        ],
        stepsAr: [
          "مقال تاريخ محتمل: تحولات القرن 19، الإمبريالية و1914، اليقظة، الضغوط على المغرب، 1918–1929، الحرب الثانية، الحماية، الاستقلال.",
          "مقال جغرافيا محتمل: التنمية، موارد المغرب، إعداد التراب، الماء والتصحر، أمريكا، الاتحاد الأوروبي، الصين.",
          "الوثائق: نصوص، خريطة، جدول، منحنى — عرّف مصطلحين، استخرج ثلاث وقائع، جملة تركيب.",
          "في الجغرافيا، خطاطة (شمال/جنوب أو محاور المغرب) تغني عن إنشاء طويل.",
        ],
      },
      courses: ["tahawulat-rasmaliya", "dughut-istimariya", "mafhum-tanmiya", "majal-maghribi", "usa-quwwa", "ue-indimaj", "chine-sa3ida", "istiqlal"],
    },
  ],
  yusuf: {
    "iman-ghayb": {
      ayah: "ذَٰلِكَ مِنْ أَنبَاءِ الْغَيْبِ نُوحِيهِ إِلَيْكَ",
      ref: "يوسف 102",
      value: "الوحي طريق معرفة الغيب",
      event: "الرؤيا التي قصّها يوسف على أبيه",
    },
    "iman-ilm": {
      ayah: "إِنَّا نَرَاكَ مِنَ الْمُحْسِنِينَ",
      ref: "يوسف 36",
      value: "العلم النافع خدمة للناس",
      event: "تعبير الرؤيا في السجن",
    },
    "hudaybiya": {
      ayah: "قَالَ لَا تَثْرِيبَ عَلَيْكُمُ الْيَوْمَ",
      ref: "يوسف 92",
      value: "العفو عند التمكين",
      event: "عفو يوسف عن إخوته بعد القدرة",
    },
    "zawaj": {
      ayah: "وَرَاوَدَتْهُ الَّتِي هُوَ فِي بَيْتِهَا عَن نَّفْسِهِ",
      ref: "يوسف 23",
      value: "الإحصان وصون الأسرة",
      event: "الفتنة في بيت العزيز",
    },
    "rasul-mufawid": {
      ayah: "فَلَمَّا دَخَلُوا عَلَيْهِ قَالُوا يَا أَيُّهَا الْعَزِيزُ",
      ref: "يوسف 88",
      value: "الحوار والإقناع",
      event: "مخاطبة الإخوة ليوسف دون أن يعرفوه",
    },
    "uthman-badhl": {
      ayah: "وَنَمِيرُ أَهْلَنَا وَنَحْفَظُ أَخَانَا",
      ref: "يوسف 65",
      value: "البذل وحفظ الأهل",
      event: "رجوع البضاعة في رحال الإخوة",
    },
    "haqq-allah-amana": {
      ayah: "إِنِّي حَفِيظٌ عَلِيمٌ",
      ref: "يوسف 55",
      value: "الأمانة في الولاية",
      event: "طلب يوسف خزائن الأرض",
    },
    "haqq-nafs-sabr": {
      ayah: "فَصَبْرٌ جَمِيلٌ وَاللَّهُ الْمُسْتَعَانُ",
      ref: "يوسف 18",
      value: "الصبر واليقين",
      event: "يعقوب بعد فقد يوسف",
    },
    "haqq-ghayr-iffa": {
      ayah: "مَعَاذَ اللَّهِ إِنَّهُ رَبِّي أَحْسَنَ مَثْوَايَ",
      ref: "يوسف 23",
      value: "العفة والحياء",
      event: "امتناع يوسف عن الفاحشة",
    },
    "iman-falsafa": {
      ayah: "إِنِ الْحُكْمُ إِلَّا لِلَّهِ",
      ref: "يوسف 40",
      value: "العقل يهتدي بالوحي",
      event: "دعوة يوسف للسجينين إلى التوحيد",
    },
    "iman-imara": {
      ayah: "اجْعَلْنِي عَلَىٰ خَزَائِنِ الْأَرْضِ",
      ref: "يوسف 55",
      value: "عمارة الأرض بالكفاءة",
      event: "تدبير القحط في مصر",
    },
    "talaq": {
      ayah: "وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ",
      ref: "يوسف 87",
      value: "لا قطع لرحم الأسرة",
      event: "يعقوب يوصي أبناءه بعد الفراق",
    },
    "riayat-atfal": {
      ayah: "قَالَ إِنِّي لَيَحْزُنُنِي أَن تَذْهَبُوا بِهِ",
      ref: "يوسف 13",
      value: "رعاية الولد وحفظه",
      event: "خوف يعقوب على يوسف",
    },
    "usra-nawaa": {
      ayah: "وَرَفَعَ أَبَوَيْهِ عَلَى الْعَرْشِ",
      ref: "يوسف 100",
      value: "لمّ شمل الأسرة",
      event: "اجتماع يعقوب وبنيه في مصر",
    },
    "rasul-bayt": {
      ayah: "وَأْتُونِي بِأَهْلِكُمْ أَجْمَعِينَ",
      ref: "يوسف 93",
      value: "بر الأهل في البيت",
      event: "دعوة يوسف أهله إلى مصر",
    },
    "haqq-bia": {
      ayah: "تَزْرَعُونَ سَبْعَ سِنِينَ دَأَبًا",
      ref: "يوسف 47",
      value: "التوسط في الموارد",
      event: "خطة يوسف لمواجهة القحط",
    },
    "kafa-istikhqa": {
      ayah: "إِنِّي حَفِيظٌ عَلِيمٌ",
      ref: "يوسف 55",
      value: "الكفاءة أساس التكليف",
      event: "يوسف يتقدم للمنصب بعلم لا بجاه",
    },
    "wiqaya-fawahish": {
      ayah: "رَبِّ السِّجْنُ أَحَبُّ إِلَيَّ مِمَّا يَدْعُونَنِي إِلَيْهِ",
      ref: "يوسف 33",
      value: "الوقاية من الفاحشة",
      event: "اختيار السجن على المعصية",
    },
    "sab3a-zill": {
      ayah: "إِنَّهُ مِنْ عِبَادِنَا الْمُخْلَصِينَ",
      ref: "يوسف 24",
      value: "الإخلاص في السر",
      event: "نجاة يوسف لأنه أخلص لله",
    },
  },
};
