window.SB_EXAM = {
  title: "L’épreuve régionale",
  kicker: "25 % du bac · 1er Bac SM et EX",
  lead:
    "Les cours du site couvrent le cadre. Cette page dit comment on te note : structure du sujet, barème, ordre des questions, piège classique. Ce n’est pas une copie d’annale officielle — c’est le plan type du CNE, pour t’entraîner sans voler un PDF.",
  drill:
    "Toutes les deux semaines : 1 production française ou 1 paragraphe HG + 1 situation d’islam (Yusuf). Le jour J, tu ne découvres pas le barème.",
  papers: [
    {
      id: "ar",
      subject: "ar",
      name: "Arabe",
      nameLong: "اللغة العربية",
      badge: "ar",
      total: 20,
      parts: [
        { title: "النصوص", points: 10, what: "Texte (مقالة، شعر، قصة) : compréhension, procédés, valeur. Preuves dans le texte, pas une bio du poète." },
        { title: "علوم اللغة", points: 4, what: "Application directe : مصادر، نسبة، تمييز، عدد، أمر/نهي، استفهام/تمني. Le وزن et le tableau battent l’intuition." },
        { title: "تعبير وإنشاء", points: 6, what: "Une compétence : توسيع فكرة، تحليل صورة، ou الربط بين الأفكار. Cohérence > volume." },
      ],
      method: [
        "Lis le texte une fois pour la thèse / le conflit, une fois pour les procédés.",
        "Langue : fais le tableau au brouillon (وزن، نوع، إعراب) avant d’écrire la phrase.",
        "Expression : reformule la consigne, puis 1 idée par phrase de lien.",
        "Relis : accords, hamza, et que tu as bien fait la compétence demandée — pas une autre.",
      ],
      trap: "Raconter le texte comme une histoire, ou coller un plan tout fait sans mots du document.",
      hurry: "Thèse en une phrase + 2 procédés + 1 exercice de langue + 8 lignes d’expression avec 2 outils de lien.",
      paper: {
        title: "Sujet type (sciences)",
        time: "Gère 2 h : 50 min texte, 20 min langue, 40 min expression, 10 min relecture.",
        steps: [
          "Document : article d’idées (تنمية، تسامح) ou poème d’إحياء / سؤال الذات, ou nouvelle courte.",
          "Questions : idée générale, parties, champ lexical, image, valeur.",
          "Langue : 2 items du cadre (ex. nombre + tamyīz, ou amr + maṣdar).",
          "Expression : توسيع d’une phrase du texte, ou analyse d’une image liée au thème.",
        ],
      },
      courses: ["maqala", "shir-ihya", "masadir", "tamyiz", "adad", "tawsi-fikra", "tahlil-sura", "rabt-afkar"],
    },
    {
      id: "fr",
      subject: "fr",
      name: "Français",
      nameLong: "Langue française",
      badge: "fr",
      total: 20,
      parts: [
        { title: "Étude de texte", points: 10, what: "Extrait d’une des trois œuvres. Situation, compréhension, champ lexical, figures, point de vue." },
        { title: "Production écrite", points: 10, what: "Lettre, essai ou dialogue. Sujet, destinataire, thèse, plan, langue et ponctuation." },
      ],
      method: [
        "Situe l’extrait (œuvre, moment, qui parle) en 3 lignes avant les questions.",
        "Pour une figure : nomme, cite, dis l’effet (ironie, pathétique, accusation).",
        "Production : 5 min de plan au brouillon. Intro courte, 2 arguments, conclusion.",
        "Dernières 5 min : accords, homophones, tu/vous selon le destinataire.",
      ],
      trap: "Résumer toute l’œuvre, ou une intro de quinze lignes et un développement vide.",
      hurry: "3 indices d’énonciation + 2 figures + production en 3 paragraphes égaux.",
      paper: {
        title: "Sujet type (toutes filières)",
        time: "Gère 2 h : 55 min texte, 55 min production, 10 min relecture.",
        steps: [
          "Texte : Boîte à merveilles (enfance, portrait), Antigone (réplique Créon–Antigone), ou Dernier Jour (peur, thèse contre la peine).",
          "Questions : locuteur, champ lexical, 2 figures, avis justifié.",
          "Production : même thème que l’extrait (lettre au directeur, essai « faut-il obéir à la loi ? », etc.).",
          "Respecte le type demandé : une lettre n’est pas un essai.",
        ],
      },
      courses: ["boite-merveilles", "antigone", "dernier-jour", "figures-style", "enonciation", "types-arguments", "production-ecrite"],
    },
    {
      id: "islam",
      subject: "islam",
      name: "Éduc. islamique",
      nameLong: "التربية الإسلامية",
      badge: "islam",
      total: 20,
      parts: [
        { title: "الوضعية", points: 8, what: "Lis la situation, formule l’إشكال, dis les attitudes des parties." },
        { title: "التعليل والاستدلال", points: 8, what: "Justifie avec le cours (تعريف، حكم، مقاصد) et une āya de Yusuf du cadre." },
        { title: "القيم والموقف", points: 4, what: "Valeur + comportement concret. Pas un sermon." },
      ],
      method: [
        "Souligne dans la situation : qui, quel conflit, quel مدخل (عقيدة، أسرة، قسط…).",
        "Écris l’إشكال en une question, pas un paragraphe.",
        "Chaque idée : notion du cadre + āya Yusuf (pas une autre sourate au hasard).",
        "Ferme par un acte (école, famille, argent, environnement).",
      ],
      trap: "Raconter Yusuf comme un film, ou coller une āya hors sujet.",
      hurry: "إشكال + 2 attitudes + 1 تعريف + 1 āya + 1 acte.",
      paper: {
        title: "Sujet type (toutes filières)",
        time: "Gère 1 h : 10 min lecture, 40 min rédaction, 10 min versets.",
        steps: [
          "Situation : deux élèves, un mariage, un dépôt d’argent, un gaspillage d’eau, une tentation — un conflit lisible.",
          "Questions types : حدد الإشكال / بين الموقف / علل / استدل من سورة يوسف / اقترح سلوكاً.",
          "Tu n’as pas à tout le programme : 1 leçon du مدخل + Yusuf suffisent si c’est juste.",
          "Apprends 8 à 10 āyas du cadre (صبر، عفة، أمانة، تمكين، عفو), pas les 111 versets par cœur.",
        ],
      },
      courses: ["surat-yusuf", "iman-ghayb", "zawaj", "haqq-nafs-sabr", "haqq-ghayr-iffa", "kafa-istikhqa"],
    },
    {
      id: "hg",
      subject: "hg",
      name: "اجتماعيات",
      nameLong: "Histoire-Géographie",
      badge: "hg",
      total: 20,
      parts: [
        { title: "Article (au choix)", points: 10, what: "Un sujet d’histoire ou de géo parmi deux. Méthode 2 pts, fond 7, forme 1." },
        { title: "Documents (l’autre matière)", points: 10, what: "Si tu rédiges l’histoire, tu travailles les docs de géo — et l’inverse. Pas les deux articles." },
      ],
      method: [
        "Choisis l’article sur la matière où tu as le plus de faits, pas « celle qui a l’air facile ».",
        "Intro : temps, lieu, enjeu, 2 questions. Corps : 2 ou 3 parties. Conclusion : bilan + ouverture.",
        "Docs : type, date, auteur, puis extraire, relier, commenter — pas recopier le document.",
        "Géo : toujours مظهر → عامل → تدخل / حد. Histoire : causes → faits → effets.",
      ],
      trap: "Une liste de dates sans phrase, ou coller WWII dans le sujet 1929.",
      hurry: "Intro de 4 lignes + 2 parties de 8 lignes + 1 carte mentale (Atlas, littoral, ou alliances 1914).",
      paper: {
        title: "Sujet type (SM / EX)",
        time: "Gère 2 h : 10 min choix, 50 min article, 50 min docs, 10 min forme.",
        steps: [
          "Article hist possible : transformations du XIXe, impérialisme et 1914, nahḍa, pressions sur le Maroc, 1918–1929, WWII, ḥimāya, indépendance.",
          "Article géo possible : développement, ressources du Maroc, aménagement, eau/désert, USA, UE, Chine.",
          "Docs : textes, carte, tableau, courbe — définir 2 termes, extraire 3 faits, une phrase de synthèse.",
          "En géo, un schéma (Nord/Sud, ou axes du Maroc) remplace souvent un roman.",
        ],
      },
      courses: ["tahawulat-rasmaliya", "dughut-istimariya", "mafhum-tanmiya", "majal-maghribi", "usa-quwwa", "ue-indimaj", "chine-sa3ida", "istiqlal"],
    },
  ],
  yusuf: {
    "iman-ghayb": {
      ayah: "ذَٰلِكَ مِنْ أَنبَاءِ الْغَيْبِ نُوحِيهِ إِلَيْكَ",
      ref: "يوسف 102",
      value: "الوحي طريق معرفة الغيب",
      event: "الرؤيا التي قصّها يوسف على أبيه",
    },
    "iman-ilm": {
      ayah: "إِنَّا نَرَاكَ مِنَ الْمُحْسِنِينَ",
      ref: "يوسف 36",
      value: "العلم النافع خدمة للناس",
      event: "تعبير الرؤيا في السجن",
    },
    "hudaybiya": {
      ayah: "قَالَ لَا تَثْرِيبَ عَلَيْكُمُ الْيَوْمَ",
      ref: "يوسف 92",
      value: "العفو عند التمكين",
      event: "عفو يوسف عن إخوته بعد القدرة",
    },
    "zawaj": {
      ayah: "وَرَاوَدَتْهُ الَّتِي هُوَ فِي بَيْتِهَا عَن نَّفْسِهِ",
      ref: "يوسف 23",
      value: "الإحصان وصون الأسرة",
      event: "الفتنة في بيت العزيز",
    },
    "rasul-mufawid": {
      ayah: "فَلَمَّا دَخَلُوا عَلَيْهِ قَالُوا يَا أَيُّهَا الْعَزِيزُ",
      ref: "يوسف 88",
      value: "الحوار والإقناع",
      event: "مخاطبة الإخوة ليوسف دون أن يعرفوه",
    },
    "uthman-badhl": {
      ayah: "وَنَمِيرُ أَهْلَنَا وَنَحْفَظُ أَخَانَا",
      ref: "يوسف 65",
      value: "البذل وحفظ الأهل",
      event: "رجوع البضاعة في رحال الإخوة",
    },
    "haqq-allah-amana": {
      ayah: "إِنِّي حَفِيظٌ عَلِيمٌ",
      ref: "يوسف 55",
      value: "الأمانة في الولاية",
      event: "طلب يوسف خزائن الأرض",
    },
    "haqq-nafs-sabr": {
      ayah: "فَصَبْرٌ جَمِيلٌ وَاللَّهُ الْمُسْتَعَانُ",
      ref: "يوسف 18",
      value: "الصبر واليقين",
      event: "يعقوب بعد فقد يوسف",
    },
    "haqq-ghayr-iffa": {
      ayah: "مَعَاذَ اللَّهِ إِنَّهُ رَبِّي أَحْسَنَ مَثْوَايَ",
      ref: "يوسف 23",
      value: "العفة والحياء",
      event: "امتناع يوسف عن الفاحشة",
    },
    "iman-falsafa": {
      ayah: "إِنِ الْحُكْمُ إِلَّا لِلَّهِ",
      ref: "يوسف 40",
      value: "العقل يهتدي بالوحي",
      event: "دعوة يوسف للسجينين إلى التوحيد",
    },
    "iman-imara": {
      ayah: "اجْعَلْنِي عَلَىٰ خَزَائِنِ الْأَرْضِ",
      ref: "يوسف 55",
      value: "عمارة الأرض بالكفاءة",
      event: "تدبير القحط في مصر",
    },
    "talaq": {
      ayah: "وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ",
      ref: "يوسف 87",
      value: "لا قطع لرحم الأسرة",
      event: "يعقوب يوصي أبناءه بعد الفراق",
    },
    "riayat-atfal": {
      ayah: "قَالَ إِنِّي لَيَحْزُنُنِي أَن تَذْهَبُوا بِهِ",
      ref: "يوسف 13",
      value: "رعاية الولد وحفظه",
      event: "خوف يعقوب على يوسف",
    },
    "usra-nawaa": {
      ayah: "وَرَفَعَ أَبَوَيْهِ عَلَى الْعَرْشِ",
      ref: "يوسف 100",
      value: "لمّ شمل الأسرة",
      event: "اجتماع يعقوب وبنيه في مصر",
    },
    "rasul-bayt": {
      ayah: "وَأْتُونِي بِأَهْلِكُمْ أَجْمَعِينَ",
      ref: "يوسف 93",
      value: "بر الأهل في البيت",
      event: "دعوة يوسف أهله إلى مصر",
    },
    "haqq-bia": {
      ayah: "تَزْرَعُونَ سَبْعَ سِنِينَ دَأَبًا",
      ref: "يوسف 47",
      value: "التوسط في الموارد",
      event: "خطة يوسف لمواجهة القحط",
    },
    "kafa-istikhqa": {
      ayah: "إِنِّي حَفِيظٌ عَلِيمٌ",
      ref: "يوسف 55",
      value: "الكفاءة أساس التكليف",
      event: "يوسف يتقدم للمنصب بعلم لا بجاه",
    },
    "wiqaya-fawahish": {
      ayah: "رَبِّ السِّجْنُ أَحَبُّ إِلَيَّ مِمَّا يَدْعُونَنِي إِلَيْهِ",
      ref: "يوسف 33",
      value: "الوقاية من الفاحشة",
      event: "اختيار السجن على المعصية",
    },
    "sab3a-zill": {
      ayah: "إِنَّهُ مِنْ عِبَادِنَا الْمُخْلَصِينَ",
      ref: "يوسف 24",
      value: "الإخلاص في السر",
      event: "نجاة يوسف لأنه أخلص لله",
    },
  },
};
