window.SB_DATA = {
  site: {
    name: "Succès Bac SM",
    bang: "!",
    arabic: "نجاح الباك",
    kicker: "1er Bac · Sciences Maths · Maroc",
    tagline:
      "La plateforme 100 % marocaine pour réussir le 1er Bac Sciences Mathématiques : maths et physique-chimie, cours vidéo, conclusions express et suivi de ta progression.",
  },
  lessons: [
    /* ——— MATHS S1 ——— */
    {
      id: "logique-mathematique",
      subject: "math",
      semester: 1,
      chapter: "Logique mathématique",
      branch: "algebre",
      durationMin: 22,
      youtubeId: "OwfPxxGx5fc",
      videoTitle: "Logique mathématique — cours 1 Bac SM",
      channel: "Math & Phys",
      basics: [
        "Une proposition est un énoncé vrai (V) ou faux (F), jamais les deux.",
        "Connecteurs : ¬ (non), ∧ (et), ∨ (ou), ⇒ (implique), ⇔ (équivaut).",
        "Quantificateurs : ∀ « pour tout », ∃ « il existe ».",
        "Méthodes : implication directe, contraposée, absurde, contre-exemple.",
      ],
      conclusion:
        "En 1er Bac SM, la logique sert à rédiger une démonstration propre. Une implication P ⇒ Q est fausse seulement si P est vraie et Q fausse. La contraposée ¬Q ⇒ ¬P est équivalente à P ⇒ Q : souvent plus simple à prouver. Un contre-exemple suffit à démolir un « pour tout ». Attention au « ou » mathématique (inclusif) et à la négation des quantificateurs : ¬(∀x, P(x)) ⇔ ∃x, ¬P(x). Si tu es pressé : retiens tables de vérité, contraposée, absurde, et la négation de ∀ / ∃.",
      formula: "¬(P ⇒ Q) ⇔ P ∧ ¬Q",
    },
    {
      id: "ensembles-applications",
      subject: "math",
      semester: 1,
      chapter: "Ensembles et applications",
      branch: "algebre",
      durationMin: 18,
      youtubeId: "XDXzXPGuZgc",
      videoTitle: "Les ensembles — définition et exemples 1er Bac SM",
      channel: "محبي الرياضيات",
      basics: [
        "Union ∪, intersection ∩, complémentaire, différence \\.",
        "Une application f : E → F associe à chaque x de E un unique f(x) dans F.",
        "Injective : f(x)=f(y) ⇒ x=y. Surjective : tout y a un antécédent. Bijective : les deux.",
        "Cardinal : |E ∪ F| = |E| + |F| − |E ∩ F|.",
      ],
      conclusion:
        "Un ensemble se décrit en extension {1,2,3} ou en compréhension {x ∈ ℝ | x>0}. Les diagrammes de Venn aident, mais en contrôle on attend les définitions. Une application n’est pas « un dessin de flèches » : c’est une règle totale et univoque. Pour la bijection, cherche l’application réciproque f⁻¹. Piège classique : confondre injective et bijective, ou oublier de vérifier que f est bien définie sur tout E. En SM, ce chapitre prépare le dénombrement et les raisonnements sur ℕ et ℝ.",
      formula: "f bijective ⇔ f injective et surjective ⇔ f⁻¹ existe",
    },
    {
      id: "generalites-fonctions",
      subject: "math",
      semester: 1,
      chapter: "Généralités sur les fonctions",
      branch: "analyse",
      durationMin: 24,
      youtubeId: "KONjMySEz9I",
      videoTitle: "Généralités sur les fonctions — 1 Bac BIOF",
      channel: "Prof fati",
      basics: [
        "Domaine de définition D_f : ensemble des x où f(x) a un sens.",
        "Parité : f(−x)=f(x) paire ; f(−x)=−f(x) impaire (D_f symétrique).",
        "Taux d’accroissement : [f(a+h)−f(a)] / h.",
        "Variations, extremums, branches infinies se préparent ici.",
      ],
      conclusion:
        "Avant toute étude, cherche D_f (dénominateur ≠ 0, racines d’indice pair ≥ 0, ln > 0). La parité réduit le travail : on étudie sur ℝ⁺ puis on symétrise. Le taux d’accroissement est le pont vers le nombre dérivé. Compare deux fonctions, encadre, et sache lire une courbe : image, antécédents, max/min. Piège : dire « f est croissante » sans préciser l’intervalle. En SM, on exige le vocabulaire exact : croissante, strictement croissante, majorée, minorée, bornée.",
      formula: "τ_a(h) = [f(a+h) − f(a)] / h",
    },
    {
      id: "barycentre-plan",
      subject: "math",
      semester: 1,
      chapter: "Le barycentre dans le plan",
      branch: "geometrie",
      durationMin: 20,
      youtubeId: "aj1293cZQn8",
      videoTitle: "Le barycentre dans le plan — cours 1 Bac",
      channel: "biadmostafa",
      basics: [
        "G barycentre de {(A,α),(B,β)} si (α+β)G⃗ = αA⃗ + βB⃗, avec α+β ≠ 0.",
        "Relation de Leibniz : ∑ α_i MG⃗_i = (∑ α_i) MG⃗.",
        "Associativité : on peut regrouper des sous-systèmes.",
        "Si ∑ α_i = 0, pas de barycentre (vecteur constant).",
      ],
      conclusion:
        "Le barycentre généralise le milieu (poids égaux). Pour montrer que G est barycentre, repars de la définition vectorielle ou de ∑ α_i GA⃗_i = 0⃗. Les poids peuvent être négatifs : G n’est alors pas « entre » les points. L’associativité simplifie les calculs à 3 points ou plus. Applications : alignement, coordonnées barycentriques, réduction de sommes vectorielles. Piège : oublier α+β ≠ 0, ou confondre barycentre et isobarycentre. En exercice, on te demande souvent de construire G puis d’écrire une relation de Chasles.",
      formula: "∑ α_i GA⃗_i = 0⃗  ⇔  G barycentre des (A_i, α_i)",
    },
    {
      id: "produit-scalaire-plan",
      subject: "math",
      semester: 1,
      chapter: "Le produit scalaire dans le plan",
      branch: "geometrie",
      durationMin: 21,
      youtubeId: "JUy-QcTULNM",
      videoTitle: "Produit scalaire — résumé complet 1re Bac",
      channel: "Driss DOTCOM",
      basics: [
        "u⃗ · v⃗ = ‖u⃗‖ ‖v⃗‖ cos θ = x_u x_v + y_u y_v dans une B.O.N.",
        "Orthogonalité : u⃗ · v⃗ = 0 (vecteurs non nuls).",
        "‖u⃗‖² = u⃗ · u⃗. Identité : ‖u+v‖² = ‖u‖² + ‖v‖² + 2 u·v.",
        "Projection orthogonale : p⃗ = [(u·v)/‖v‖²] v⃗.",
      ],
      conclusion:
        "Le produit scalaire mesure l’alignement de deux vecteurs. En base orthonormée, utilise les coordonnées : plus rapide que cosinus. Pour prouver un angle droit, montre un produit scalaire nul. Pour une longueur, passe par ‖u‖². Formules de polarisation et théorème de Pythagore / Al-Kashi en découlent. Piège : appliquer x1x2+y1y2 hors base orthonormée, ou oublier le signe du cosinus (angle obtus). En SM, tu dois aussi exprimer une distance d’un point à une droite via le produit scalaire.",
      formula: "u⃗ · v⃗ = ‖u⃗‖ ‖v⃗‖ cos(u⃗, v⃗)",
    },
    {
      id: "calcul-trigonometrique",
      subject: "math",
      semester: 1,
      chapter: "Calcul trigonométrique",
      branch: "analyse",
      durationMin: 25,
      youtubeId: "9CJrhefj7VM",
      videoTitle: "Calcul trigonométrique — séance 1, 1 Bac",
      channel: "maths variés",
      basics: [
        "Cercle trigo : cos²x + sin²x = 1 ; tan x = sin x / cos x.",
        "Angles associés : π−x, π+x, −x, π/2−x…",
        "Addition : cos(a±b), sin(a±b), tan(a±b).",
        "Duplication : cos 2a = 2cos²a − 1 = 1 − 2sin²a.",
      ],
      conclusion:
        "Le calcul trigonométrique du 1er Bac SM, c’est d’abord le cercle et les formules d’addition, pas une calculatrice. Pour linéariser un produit, utilise cos a cos b, etc. Pour résoudre cos x = cos α : x = ±α + 2kπ. Pour sin : x = α + 2kπ ou x = π−α + 2kπ. Piège : domaines de tan et les valeurs interdites, ou se tromper de formule d’angle associé. En contrôle, on attend une réduction exacte (pas 0,707). Entraîne-toi à passer de tan à sin/cos et à factoriser avec les identités.",
      formula: "cos(a−b) = cos a cos b + sin a sin b",
    },
    {
      id: "suites-numeriques",
      subject: "math",
      semester: 1,
      chapter: "Les suites numériques",
      branch: "analyse",
      durationMin: 28,
      youtubeId: "v97yivUfzRY",
      videoTitle: "Les suites numériques 1 Bac — cours détaillé",
      channel: "Chadyyy",
      basics: [
        "Suite arithmétique : u_{n+1} = u_n + r ; u_n = u_0 + n r.",
        "Suite géométrique : u_{n+1} = q u_n ; u_n = u_0 q^n.",
        "Monotonie : comparer u_{n+1}−u_n ou u_{n+1}/u_n (si >0).",
        "Convergence : limite finie ; divergente vers ±∞ ou sans limite.",
      ],
      conclusion:
        "Une suite est une fonction de ℕ (ou ℕ*) vers ℝ. Reconnaître arithmétique / géométrique évite 80 % des pièges. Pour une récurrence u_{n+1}=f(u_n), étudie f, les points fixes, et encadre. Somme arithmétique : n(u_1+u_n)/2. Somme géométrique : u_0 (1−q^{n+1})/(1−q) si q≠1. Piège : dire qu’une suite croissante converge (il faut qu’elle soit majorée). En SM, on te demandera aussi la limite par comparaison, et parfois une démonstration par récurrence sur une inégalité.",
      formula: "S_n = u_0 (1 − q^{n+1}) / (1 − q)   (q ≠ 1)",
    },
    {
      id: "limites-fonction",
      subject: "math",
      semester: 1,
      chapter: "Limites d’une fonction",
      branch: "analyse",
      durationMin: 26,
      youtubeId: "BI9MEDbcqWA",
      videoTitle: "Limites des fonctions — 1 Bac SM et S.Exp",
      channel: "taalom riyadiyate",
      basics: [
        "Limite en a, en ±∞ ; limites à gauche / à droite.",
        "Opérations : somme, produit, quotient (si dénominateur ≠ 0).",
        "Formes indéterminées : ∞−∞, 0/0, ∞/∞, 0×∞…",
        "Asymptotes : verticale x=a, horizontale y=ℓ, oblique y=mx+p.",
      ],
      conclusion:
        "Calculer une limite, c’est lever une indétermination : factoriser, multiplier par le conjugué, mettre x² en facteur, ou comparer. Une limite à droite différente de la gauche ⇒ pas de limite en a. L’asymptote verticale apparaît si f(x) → ±∞ quand x → a. Piège : « simplifier » un 0/0 sans factoriser vraiment, ou conclure trop vite qu’une FI vaut 0. En SM, on attend aussi le théorème des gendarmes et les limites de référence (sin x / x → 1, etc.) quand le programme les autorise.",
      formula: "lim_{x→0} (sin x)/x = 1",
    },
    {
      id: "rotation-plan",
      subject: "math",
      semester: 1,
      chapter: "La rotation dans le plan",
      branch: "geometrie",
      durationMin: 19,
      youtubeId: "IzvJpdAuWb8",
      videoTitle: "La rotation dans le plan — 1 Bac SM",
      channel: "biadmostafa",
      basics: [
        "Rotation r de centre Ω et d’angle θ : r(Ω)=Ω, (ΩM, ΩM') = θ, ‖ΩM‖=‖ΩM'‖.",
        "Composée de deux rotations : rotation ou translation.",
        "L’angle est orienté ; θ et θ+2π définissent la même rotation.",
        "Expression complexe (si vu) : z' − ω = e^{iθ}(z − ω).",
      ],
      conclusion:
        "Une rotation conserve les distances et les angles orientés : c’est un isométrie directe. Pour construire M', reporte l’angle θ autour de Ω et garde la même longueur. Pour montrer qu’une application est une rotation, identifie le centre (point fixe) et l’angle. La composée de deux rotations de même centre est une rotation d’angle somme. Piège : confondre rotation et homothétie, ou oublier l’orientation (sens trigo). En SM, relie ce chapitre au produit scalaire (cosinus de l’angle) et aux nombres complexes si ton prof les a déjà introduits en construction.",
      formula: "z' − ω = e^{iθ} (z − ω)",
    },

    /* ——— MATHS S2 ——— */
    {
      id: "derivation",
      subject: "math",
      semester: 2,
      chapter: "La dérivation",
      branch: "analyse",
      durationMin: 32,
      youtubeId: "t6QJ7E5_ubE",
      videoTitle: "Dérivabilité — 1re Bac SM",
      channel: "محبي الرياضيات",
      basics: [
        "f'(a) = lim_{h→0} [f(a+h)−f(a)]/h si la limite existe.",
        "(u+v)'=u'+v', (uv)'=u'v+uv', (u/v)'=(u'v−uv')/v², (u∘v)'=(u'∘v)·v'.",
        "Tangente en a : y = f'(a)(x−a) + f(a).",
        "Signe de f' ⇒ variations de f.",
      ],
      conclusion:
        "La dérivée est le taux d’accroissement instantané et la pente de la tangente. Apprends par cœur les dérivées usuelles (x^n, √x, 1/x, sin, cos, tan) puis les opérations. Une fonction peut être continue sans être dérivable (angle, |x| en 0). Pour un extremum intérieur, f'(c)=0 n’est pas suffisant : lis le tableau de signes. Piège : dériver un quotient trop vite, ou oublier la chaîne (u∘v). En SM, on te demandera aussi la dérivée n-ième simple et l’interprétation cinématique (vitesse = dérivée de la position).",
      formula: "(u ∘ v)' = (u' ∘ v) · v'",
    },
    {
      id: "etude-fonctions",
      subject: "math",
      semester: 2,
      chapter: "Étude des fonctions",
      branch: "analyse",
      durationMin: 30,
      youtubeId: "iVKHtFr25vM",
      videoTitle: "Étude des fonctions — branches infinies 1re Bac SM",
      channel: "محبي الرياضيات",
      basics: [
        "Plan d’étude : D_f, parité, limites, f', tableau, asymptotes, courbe.",
        "Asymptote oblique : f(x) = mx + p + ε(x) avec ε→0.",
        "Convexité / inflexion via f'' si le programme le demande.",
        "Position relative : signe de f−g.",
      ],
      conclusion:
        "L’étude de fonction est le chapitre « examen » du 1er Bac SM. Suis toujours le même plan pour ne rien oublier. Les limites aux bornes de D_f donnent les branches infinies. Une asymptote oblique se trouve en calculant lim (f(x)−mx−p). Le tableau de variations doit coller au signe de f', pas à l’intuition. Piège : tracer une courbe qui contredit les limites, ou inventer un extremum. En SM, soigne la rédaction : « f est dérivable sur… », « d’où le tableau », « donc C_f admet… ».",
      formula: "m = lim_{x→∞} f(x)/x ,   p = lim_{x→∞} [f(x) − m x]",
    },
    {
      id: "vecteurs-espace",
      subject: "math",
      semester: 2,
      chapter: "Vecteurs de l’espace",
      branch: "geometrie",
      durationMin: 20,
      youtubeId: "Y2PdIucQya4",
      videoTitle: "Vecteurs dans l’espace — 1 Bac SM",
      channel: "biadmostafa",
      basics: [
        "Vecteurs colinéaires : il existe k, u⃗ = k v⃗.",
        "Coplanaires : mélange linéaire nulle non triviale, ou déterminant nul.",
        "Repère (O; i⃗,j⃗,k⃗) : M(x,y,z) ⇔ OM⃗ = x i⃗ + y j⃗ + z k⃗.",
        "Chasles reste vrai dans l’espace.",
      ],
      conclusion:
        "L’espace ajoute une troisième dimension : on ne peut plus tout dessiner comme au plan. Colinéarité de deux vecteurs = proportionnalité des 3 coordonnées. Trois vecteurs coplanaires s’expriment l’un en fonction des autres. Un repère affine permet de passer au calcul. Piège : utiliser un produit scalaire 2D, ou conclure à la colinéarité avec deux coordonnées seulement. Ce chapitre ouvre la géométrie analytique de l’espace (droites, plans) du semestre 2.",
      formula: "u⃗ ∧ v⃗ = 0⃗  ⇔  u⃗ et v⃗ colinéaires",
    },
    {
      id: "geometrie-espace",
      subject: "math",
      semester: 2,
      chapter: "Géométrie dans l’espace",
      branch: "geometrie",
      durationMin: 24,
      youtubeId: "L__igVGAb9o",
      videoTitle: "Géométrie dans l’espace — méthodes d’exercices",
      channel: "Aderdour Mustapha",
      basics: [
        "Droite : point + vecteur directeur. Plan : point + 2 vecteurs non colinéaires.",
        "Équation cartésienne d’un plan : ax+by+cz+d=0, n⃗=(a,b,c) normal.",
        "Parallélisme / orthogonalité via vecteurs directeurs et normales.",
        "Intersection : résoudre un système.",
      ],
      conclusion:
        "En espace, une droite n’a pas d’équation cartésienne unique « simple » comme au plan : on préfère une représentation paramétrique. Un plan, lui, a une équation ax+by+cz+d=0. Pour l’orthogonalité droite/plan : directeur colinéaire à la normale. Pour le parallélisme de deux plans : normales colinéaires. Piège : confondre orthogonalité de droites et de plans. Méthode SM : traduis tout en vecteurs, puis calcule. Les exercices types : intersection, distance, section plane.",
      formula: "Plan : ax + by + cz + d = 0",
    },
    {
      id: "denombrement",
      subject: "math",
      semester: 2,
      chapter: "Dénombrement",
      branch: "proba",
      durationMin: 22,
      youtubeId: "yODTn0TfAak",
      videoTitle: "Le dénombrement — 1 Bac SM",
      channel: "biadmostafa",
      basics: [
        "Principe : cardinal d’un produit cartésien, p×q choix successifs.",
        "Permutations : n! arrangements de n objets distincts.",
        "Arrangements A_n^p = n! / (n−p)! (ordre important).",
        "Combinaisons C_n^p = n! / (p!(n−p)!) (ordre indifférent).",
      ],
      conclusion:
        "Avant de calculer, décide si l’ordre compte et si les répétitions sont permises. C’est 90 % de l’exercice. Un comité de 3 personnes parmi 10 : C_10^3. Un code à 4 chiffres distincts : A_10^4. Un mot de 4 lettres avec répétition : 26^4. Piège : utiliser C_n^p alors que l’ordre compte (classement, podium). En SM, on relie souvent ce chapitre aux probabilités d’un univers fini équiprobable : P(A)=|A|/|Ω|. Dessine un arbre si tu doutes.",
      formula: "C_n^p = n! / (p! (n−p)!)",
    },
    {
      id: "produit-scalaire-espace",
      subject: "math",
      semester: 2,
      chapter: "Le produit scalaire dans l’espace",
      branch: "geometrie",
      durationMin: 20,
      youtubeId: "3EZdqEbDQV0",
      videoTitle: "Produit scalaire dans l’espace — Bac 1 SM",
      channel: "RIAMATH",
      basics: [
        "u⃗·v⃗ = ‖u‖‖v‖ cos θ = xx'+yy'+zz' en B.O.N.",
        "Plan orthogonal à n⃗ : n⃗ · AM⃗ = 0.",
        "Distance d’un point à un plan : |ax+by+cz+d|/√(a²+b²+c²).",
        "Aire, orthogonalité, projections : mêmes idées qu’au plan.",
      ],
      conclusion:
        "Le produit scalaire 3D est le même objet qu’au plan, avec une coordonnée de plus. L’équation d’un plan s’interprète comme « vecteur normal · vecteur du plan = 0 ». Pour un angle entre deux droites, prends les directeurs. Pour un angle droite/plan, passe par le complémentaire avec la normale. Piège : formule de distance oubliée, ou normale mal lue dans l’équation. En SM, ce chapitre fusionne avec la géométrie analytique : un seul langage vectoriel pour tout l’espace.",
      formula: "d(M, plan) = |ax+by+cz+d| / √(a²+b²+c²)",
    },
    {
      id: "arithmetique-z",
      subject: "math",
      semester: 2,
      chapter: "Arithmétique dans ℤ",
      branch: "algebre",
      durationMin: 27,
      youtubeId: "Ckdj31egfRs",
      videoTitle: "Arithmétique dans ℤ — division euclidienne",
      channel: "JAMMOUA MATH ACADEMY",
      basics: [
        "Division euclidienne : a = bq + r, 0 ≤ r < |b|.",
        "PGCD : algorithme d’Euclide. PPCM · PGCD = |ab| si a,b ≠ 0.",
        "Bézout : il existe u,v, au+bv = pgcd(a,b).",
        "Gauss : si a|bc et pgcd(a,b)=1 alors a|c. Nombres premiers, congruences.",
      ],
      conclusion:
        "L’arithmétique SM, c’est la division euclidienne + Euclide + Bézout + Gauss. Pour résoudre ax+by=c, une solution existe ssi pgcd(a,b) divise c. Les congruences a ≡ b [n] simplifient les puissances et les critères de divisibilité. Piège : oublier que les coefficients de Bézout peuvent être négatifs, ou appliquer Gauss sans coprimalité. En contrôle, rédige Euclide en cascade jusqu’au reste 0, puis remonte pour Bézout. C’est un chapitre très « points faciles » si la méthode est mécanique.",
      formula: "au + bv = pgcd(a,b)   (Bézout)",
    },
    {
      id: "produit-vectoriel",
      subject: "math",
      semester: 2,
      chapter: "Le produit vectoriel",
      branch: "geometrie",
      durationMin: 18,
      youtubeId: "d2xxyN-nVwE",
      videoTitle: "Géométrie dans l’espace — 1 Bac SM",
      channel: "biadmostafa",
      basics: [
        "u⃗ ∧ v⃗ est orthogonal à u⃗ et v⃗, sens de la règle de la main droite.",
        "‖u⃗ ∧ v⃗‖ = ‖u‖‖v‖ sin θ = aire du parallélogramme.",
        "En B.O.N. directe : déterminant 3×3 des coordonnées.",
        "u ∧ v = 0⃗ ⇔ colinéaires. Mixte : (u∧v)·w = volume.",
      ],
      conclusion:
        "Le produit vectoriel est l’outil SM pour l’aire, le plan (vecteur normal u∧v) et le volume (produit mixte). Il n’est pas commutatif : v∧u = −(u∧v). Calcule-le par déterminant pour éviter les erreurs de signes. Piège : oublier le sens (base directe) ou utiliser un produit vectoriel au plan 2D sans plonger dans l’espace. Si tu es pressé : normal au plan = AB ∧ AC, aire du triangle = (1/2)‖AB ∧ AC‖, volume du tétraèdre = (1/6)|mixte|.",
      formula: "‖u⃗ ∧ v⃗‖ = ‖u⃗‖ ‖v⃗‖ |sin θ|",
    },

    /* ——— PC PHYSIQUE S1 ——— */
    {
      id: "rotation-solide",
      subject: "pc",
      semester: 1,
      chapter: "Rotation d’un solide indéformable autour d’un axe fixe",
      branch: "physique",
      durationMin: 20,
      youtubeId: "xEVnaXV80Y0",
      videoTitle: "Rotation d’un solide autour d’un axe fixe — 1er Bac",
      channel: "Prof Barii Physique",
      basics: [
        "Solide indéformable : distances entre points constantes.",
        "Vitesse linéaire : v = r ω (ω en rad/s).",
        "Période T, fréquence f = 1/T, ω = 2π f.",
        "Tous les points ont le même ω, pas la même v.",
      ],
      conclusion:
        "Un solide en rotation autour d’un axe fixe tourne d’un même angle en un même temps : ω est commun. Plus un point est loin de l’axe, plus il va vite (v=rω). Convertis toujours les tours/min en rad/s : ω = 2πN/60. Piège : utiliser v=ω pour tous les points, ou oublier le rayon. Ce chapitre pose le vocabulaire (axe, tour, radian) avant travail et énergie. En SM, on te demandera souvent de relier N (tr/min), T et v d’un point périphérique.",
      formula: "v = r ω    et    ω = 2π / T",
    },
    {
      id: "travail-puissance-force",
      subject: "pc",
      semester: 1,
      chapter: "Travail et puissance d’une force",
      branch: "physique",
      durationMin: 22,
      youtubeId: "j-G086IsAMQ",
      videoTitle: "Travail et puissance d’une force — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "W(F) = F · AB⃗ = F AB cos α (force constante).",
        "Travail moteur (W>0), résistant (W<0), nul si force ⊥ déplacement.",
        "Puissance P = W/Δt = F v cos α.",
        "Unités : W en joule (J), P en watt (W).",
      ],
      conclusion:
        "Le travail mesure l’énergie transférée par une force lors d’un déplacement. Seule la composante parallèle compte. Le poids : W(P) = mgh si on descend de h (selon l’orientation du z). Une force de frottement de norme constante : W = −f × ℓ. Piège : oublier le signe, ou prendre α comme l’angle avec la verticale au lieu du déplacement. Puissance moyenne ≠ puissance instantanée. En exercice SM, on enchaîne souvent plusieurs forces : le travail total est la somme algébrique.",
      formula: "W(F⃗) = F × AB × cos α",
    },
    {
      id: "travail-energie-cinetique",
      subject: "pc",
      semester: 1,
      chapter: "Travail et énergie cinétique",
      branch: "physique",
      durationMin: 18,
      youtubeId: "wH8wyQM0uRw",
      videoTitle: "Énergie cinétique — 1 Bac SM",
      channel: "EasyPhysi SUP",
      basics: [
        "Énergie cinétique : E_c = ½ m v² (translation).",
        "Théorème : ΔE_c = ∑ W(F) entre A et B.",
        "m en kg, v en m/s, E_c en J.",
        "Utile pour trouver une vitesse sans passer par a=F/m.",
      ],
      conclusion:
        "Le théorème de l’énergie cinétique relie la variation de ½mv² à la somme des travaux. C’est souvent plus court que Newton + cinématique. Inclus toutes les forces (poids, frottements, tension…). Piège : oublier un travail, ou utiliser ½mv² avec v en km/h. Pour un solide en rotation, le programme SM reste en général sur la translation du centre / un point, sauf si le prof a défini E_c de rotation. Méthode : état initial, état final, bilan des travaux, résoudre pour v ou pour f.",
      formula: "ΔE_c = E_c(B) − E_c(A) = ∑ W_{A→B}(F⃗)",
    },
    {
      id: "energie-mecanique",
      subject: "pc",
      semester: 1,
      chapter: "Travail et énergie potentielle de pesanteur — Énergie mécanique",
      branch: "physique",
      durationMin: 20,
      youtubeId: "SSrqPDEXGHo",
      videoTitle: "Résumé : énergie mécanique — 1 BAC",
      channel: "Prof Malak",
      basics: [
        "E_pp = m g z (z axe vertical orienté vers le haut, origine choisie).",
        "E_m = E_c + E_pp.",
        "Si seules les forces conservatives travaillent, E_m se conserve.",
        "Frottements ⇒ E_m diminue : ΔE_m = W(non conservatives).",
      ],
      conclusion:
        "L’énergie potentielle de pesanteur dépend du zéro choisi, mais les variations ΔE_pp = mgΔz n’en dépendent pas. Conservation de E_m ⇔ pas de frottement (ou travail nul des forces non conservatives). Sinon : ΔE_m = W(frottements). Piège : mélanger z vers le bas et la formule mgz, ou dire que E_m se conserve « toujours ». En SM, un exercice type : glisser sur un plan, trouver v en bas, puis la hauteur si un f intervient. Toujours définir le référentiel et l’axe z.",
      formula: "E_m = ½ m v² + m g z",
    },
    {
      id: "energie-interne",
      subject: "pc",
      semester: 1,
      chapter: "Travail et énergie interne",
      branch: "physique",
      durationMin: 16,
      youtubeId: "n1-CjpL7EVM",
      videoTitle: "Travail et énergie interne — 1 Bac SM",
      channel: "Prof Ridouan",
      basics: [
        "Énergie interne U : énergie microscopique (agitation, liaisons).",
        "Premier principe (forme lycée) : ΔU = W + Q.",
        "W : travail (souvent des forces de pression), Q : chaleur.",
        "Signe : reçu par le système > 0 (convention usuelle au lycée marocain à vérifier chez ton prof).",
      ],
      conclusion:
        "Ici on quitte le point matériel pour un système qui peut chauffer. L’énergie interne change si on lui fournit du travail ou de la chaleur. Un frottement « perdu » en mécanique se retrouve souvent en Q (échauffement). Piège : confondre U avec E_c macroscopique, ou oublier la convention de signes de ton manuel. En SM, relie ce chapitre à l’énergie mécanique : ce qui n’est plus mécanique est devenu interne / thermique. Reste concret : compression, frottement, chauffage.",
      formula: "ΔU = W + Q",
    },
    {
      id: "energie-thermique",
      subject: "pc",
      semester: 1,
      chapter: "Énergie thermique et transfert thermique",
      branch: "physique",
      durationMin: 18,
      youtubeId: "EkoIunDPzuE",
      videoTitle: "Énergie thermique, transfert, calorimétrie — 1 Bac SM",
      channel: "Hassan EL OMRANI",
      basics: [
        "Q = m c Δθ (chauffage sans changement d’état).",
        "Changement d’état : Q = m L (fusion, vaporisation…).",
        "Équilibre : somme des Q = 0 dans un calorimètre isolé.",
        "c : capacité thermique massique (J·kg⁻¹·°C⁻¹).",
      ],
      conclusion:
        "La calorimétrie du 1er Bac SM, c’est un bilan d’énergie thermique. L’eau qui se refroidit cède Q < 0 ; le métal qui se chauffe reçoit Q > 0. Sans perte : ∑Q = 0. Attention aux unités (g vs kg) et aux changements d’état (on reste à θ constante pendant la fusion). Piège : utiliser mcΔθ pendant une fusion. Conduction, convection, rayonnement : trois modes de transfert, à citer même si le calcul est surtout calorimétrique. Prépare les valeurs de c de l’eau : 4180 J·kg⁻¹·°C⁻¹.",
      formula: "Q = m c Δθ    ;    Q = m L",
    },

    /* ——— PC CHIMIE S1 ——— */
    {
      id: "mesure-chimie",
      subject: "pc",
      semester: 1,
      chapter: "Importance de la mesure en chimie",
      branch: "chimie",
      durationMin: 14,
      youtubeId: "87F9PMeK-P8",
      videoTitle: "Importance de la mesure en chimie — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "Mesure = valeur + unité + incertitude.",
        "Chiffres significatifs : ne pas afficher plus que l’appareil.",
        "Erreur relative = |écart| / valeur de référence.",
        "Fidélité (répétabilité) ≠ justesse (proche de la vraie valeur).",
      ],
      conclusion:
        "La chimie quantitative commence par mesurer correctement : masse, volume, concentration. Une burette n’a pas la même précision qu’une éprouvette : choisis l’instrument. L’incertitude se propage dans un calcul (somme : on additionne les incertitudes ; produit : on passe par le relatif). Piège : écrire 1,23456 mol·L⁻¹ avec une balance au 0,1 g. En SM, on te demandera d’estimer si un résultat est acceptable (écart relatif < 5 % souvent). Ce chapitre est court mais il note tous les TP de l’année.",
      formula: "δ_relatif = |x_mes − x_ref| / |x_ref|",
    },
    {
      id: "quantite-matiere",
      subject: "pc",
      semester: 1,
      chapter: "Grandeurs physiques liées à la quantité de matière",
      branch: "chimie",
      durationMin: 18,
      youtubeId: "jq2nGFX7OL4",
      videoTitle: "Grandeurs physiques liées à la quantité de matière — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "n = m / M ; n = c V ; n = V / V_m (gaz, V_m ≈ 24 L·mol⁻¹ souvent).",
        "M : masse molaire (g·mol⁻¹). N_A ≈ 6,02×10²³ mol⁻¹.",
        "Concentration massique t = m/V ; molaire c = n/V.",
        "Conversion : c = t / M.",
      ],
      conclusion:
        "Toute la chimie de 1er Bac passe par n, la quantité de matière. Convertis tout en mole avant un tableau d’avancement. Pour un gaz, vérifie si V_m est donné (22,4 ou 24 L·mol⁻¹ selon T,P). Piège : mélanger mL et L (V en litre dans c=n/V SI), ou utiliser M du composé au lieu de l’espèce demandée. En SM, entraîne-toi à passer de la bouteille (étiquette en g/L) à c en mol·L⁻¹. Sans ce réflexe, les dosages et l’avancement deviennent impossibles.",
      formula: "n = m/M = cV = N/N_A",
    },
    {
      id: "solutions-electrolytiques",
      subject: "pc",
      semester: 1,
      chapter: "Solutions électrolytiques et concentrations",
      branch: "chimie",
      durationMin: 16,
      youtubeId: "faDFAM1AibA",
      videoTitle: "Concentration et solutions électrolytiques — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "Électrolyte : se dissocie en ions (NaCl → Na⁺ + Cl⁻).",
        "Conservation de la charge et de la matière en solution.",
        "Dilution : c1 V1 = c2 V2.",
        "Conductivité liée à la concentration et à la nature des ions.",
      ],
      conclusion:
        "Une solution électrolytique contient des ions libres qui conduisent le courant. Écris la dissolution ionique avec les bons coefficients (CaCl2 → Ca²⁺ + 2 Cl⁻). La dilution conserve n du soluté : c1V1=c2V2. Piège : oublier les coefficients stœchiométriques des ions, ou diluer sans convertir les volumes. En SM, ce chapitre prépare conductimétrie et titrages : on suit souvent [X] au cours du temps ou du volume versé. Toujours préciser l’espèce (ion, molécule) dont on parle.",
      formula: "c_1 V_1 = c_2 V_2  (dilution)",
    },
    {
      id: "suivi-transformation",
      subject: "pc",
      semester: 1,
      chapter: "Suivi d’une transformation chimique",
      branch: "chimie",
      durationMin: 20,
      youtubeId: "aGy-ny5Vu1M",
      videoTitle: "Suivi d’une transformation chimique — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "Tableau d’avancement : n_i, −νx, n_f = n_i + νx (ν algébrique).",
        "Réactif limitant : celui qui s’annule en premier (x_max).",
        "Avancement final x_f ≤ x_max ; réaction totale si égalité.",
        "Suivi : pression, masse, conductivité, spectrophotometrie…",
      ],
      conclusion:
        "Le tableau d’avancement est l’outil central. Une ligne par espèce, une colonne état initial / en cours / final. Trouve x_max en testant quel réactif s’annule. Si la réaction n’est pas totale, x_f se mesure ( palier de conductivité, volume de gaz…). Piège : coefficients stœchiométriques oubliés dans −νx, ou unités de n incohérentes. En SM, on enchaîne souvent suivi expérimental + modèle. Rédige : « le réactif limitant est… donc x_max=… ».",
      formula: "n(X) = n_0(X) + ν_X · x",
    },
    {
      id: "conductimetrie",
      subject: "pc",
      semester: 1,
      chapter: "Mesure des quantités de matière en solution par conductimétrie",
      branch: "chimie",
      durationMin: 17,
      youtubeId: "zlKKGimE1Ks",
      videoTitle: "Conductance et conductivité — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "σ = ∑ λ_i [X_i] (à dilution infinie, loi de Kohlrausch lycée).",
        "σ diminue ou augmente selon que les ions conducteurs disparaissent.",
        "Équivalence : rupture de pente sur σ = f(V).",
        "Permet de trouver c inconnue sans indicateur coloré.",
      ],
      conclusion:
        "La conductimétrie suit les ions. Quand on verse un réactif, σ change parce que la nature et la concentration des ions changent. À l’équivalence, le réactif limitant s’inverse : la pente de σ(V) casse. On lit V_E, puis n = c V. Piège : oublier que l’eau et les ions spectateurs comptent, ou ne pas diluer correctement (volume total). En SM, on te donne souvent λ (conductivités molaires) : recalcule σ théorique et compare à la courbe. C’est un TP / exercice très fréquent au régional.",
      formula: "σ ≈ ∑ λ_i [X_i]",
    },
    {
      id: "acido-basiques",
      subject: "pc",
      semester: 1,
      chapter: "Les réactions acido-basiques",
      branch: "chimie",
      durationMin: 22,
      youtubeId: "I2zTQcnlavY",
      videoTitle: "Réactions acido-basiques — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "Brönsted : acide = donneur de H⁺, base = accepteur.",
        "Couple acide/base : AH / A⁻. Ampholyte : H2O, HCO3⁻…",
        "pH = −log [H3O⁺] (solution aqueuse diluée).",
        "Réaction acide fort + base forte : H3O⁺ + HO⁻ → 2 H2O.",
      ],
      conclusion:
        "Identifie toujours les couples. Un acide fort est totalement dissocié ; un acide faible, non (équilibre). L’eau est à la fois acide et base (amphotère), Ke = [H3O⁺][HO⁻] = 1,0×10⁻¹⁴ à 25 °C. Piège : écrire HCl comme molécule en solution diluée, ou calculer le pH d’un acide faible comme un fort. En SM, tu dois écrire l’équation de la réaction prépondérante et reconnaître si elle est totale. C’est la base des dosages du chapitre suivant.",
      formula: "pH = −log [H3O⁺]    ;    K_e = 10⁻¹⁴ (25 °C)",
    },
    {
      id: "oxydoreduction",
      subject: "pc",
      semester: 1,
      chapter: "Les réactions d’oxydo-réduction",
      branch: "chimie",
      durationMin: 22,
      youtubeId: "oRX2L9zDtq4",
      videoTitle: "Réactions d’oxydoréduction — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "Oxydation : perte d’électrons. Réduction : gain d’électrons.",
        "Couple Ox/Red. L’oxydant du couple 1 réagit avec le réducteur du couple 2.",
        "Demi-équations, puis bilan sans e⁻.",
        "Nombres d’oxydation pour vérifier.",
      ],
      conclusion:
        "Méthode : écris les deux demi-équations, multiplie pour égaler les e⁻, additionne. En solution aqueuse, on peut avoir H2O, H⁺ ou HO⁻ pour équilibrer O et H. Piège : inverser oxydant et réducteur, ou laisser des électrons dans le bilan. En SM, les couples classiques (MnO4⁻/Mn²⁺, I2/I⁻, Fe³⁺/Fe²⁺, Zn²⁺/Zn) reviennent tout le temps. Un oxydant fort oxyde un réducteur fort : tu n’as pas encore le tableau complet des E°, donc on te donne souvent « la réaction a lieu » ou les couples à utiliser.",
      formula: "Ox_1 + Red_2 → Red_1 + Ox_2",
    },
    {
      id: "dosages-directs",
      subject: "pc",
      semester: 1,
      chapter: "Les dosages (titrages) directs",
      branch: "chimie",
      durationMin: 20,
      youtubeId: "swPRyee5Cpg",
      videoTitle: "Dosage direct — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "À l’équivalence : les réactifs ont été introduits dans les proportions stœchiométriques.",
        "c_A V_A = k c_B V_E (k selon les coefficients).",
        "Indicateur coloré, pH-métrie ou conductimétrie pour V_E.",
        "Dosage direct = réaction rapide, totale, unique.",
      ],
      conclusion:
        "Un titrage direct sert à trouver une concentration inconnue. On verse le réactif titrant jusqu’à l’équivalence. Relie n_inconnu et n_versé par la stœchiométrie. Piège : oublier le facteur 2 (H2SO4, H2C2O4…), ou lire V_E sur le mauvais axe. En SM, on attend le tableau d’avancement à l’équivalence et parfois l’incertitude sur V_E. Choisis un indicateur dont la zone de virage contient le pH à l’équivalence. Rédige l’équation, puis « à l’équivalence, n(A)/ν_A = n(B)/ν_B ».",
      formula: "n(titré)/ν_titré = n(titrant)/ν_titrant   (à l’équivalence)",
    },

    /* ——— PC PHYSIQUE S2 ——— */
    {
      id: "champ-electrostatique",
      subject: "pc",
      semester: 2,
      chapter: "Champ électrostatique",
      branch: "physique",
      durationMin: 20,
      youtubeId: "XeYLQGV6Iz4",
      videoTitle: "Le champ électrostatique — 1 BAC SM",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "E⃗ tel que F⃗ = q E⃗. Unité : N·C⁻¹ ou V·m⁻¹.",
        "Charge ponctuelle : E = k |q| / r², k = 9×10⁹ SI.",
        "Lignes de champ : sortent de + , aboutissent à −.",
        "Champ uniforme entre deux armatures : E = U / d.",
      ],
      conclusion:
        "Le champ électrostatique décrit la force qu’une charge q subirait : F=qE (attention au signe de q). Superposition : E⃗ total = somme vectorielle. Entre les plaques d’un condensateur (plan), E est uniforme et orthogonal aux armatures. Piège : oublier que E est un vecteur, ou utiliser kq/r au lieu de kq/r². En SM, on te demandera souvent le mouvement d’une charge dans un champ uniforme (parabole analogue à la pesanteur). Relie E et la tension U=Ed pour les exercices d’accélérateur simple.",
      formula: "F⃗ = q E⃗    ;    E = k |q| / r²",
    },
    {
      id: "energie-potentielle-electrique",
      subject: "pc",
      semester: 2,
      chapter: "Énergie potentielle d’une charge dans un champ électrique uniforme",
      branch: "physique",
      durationMin: 16,
      youtubeId: "vMXcKvmC4g8",
      videoTitle: "Énergie potentielle électrostatique — 1 BAC BIOF SM",
      channel: "Académie physique chimie",
      basics: [
        "E_pe = q V + const. Dans un champ uniforme : E_pe = q E z (+const).",
        "W(F_élec) = −ΔE_pe (force conservative).",
        "U = V_A − V_B = E d si E uniforme, d selon les lignes de champ.",
        "Une charge + descend le potentiel ; une − le remonte.",
      ],
      conclusion:
        "Comme mgz pour la pesanteur, qEz (ou qV) pour l’électrostatique uniforme. Le travail de la force électrique ne dépend pas du chemin. L’énergie mécanique E_c + E_pe se conserve s’il n’y a pas d’autre force qui travaille. Piège : le signe de q, et l’orientation de l’axe. En SM, exercices types : accélération d’un électron entre deux plaques, vitesse à la sortie, ou « hauteur » maximale analogue au lancer. Toujours dessiner + / − des armatures et le sens de E⃗.",
      formula: "ΔE_pe = q (V_final − V_initial)",
    },
    {
      id: "transfert-energie-circuit",
      subject: "pc",
      semester: 2,
      chapter: "Transfert d’énergie dans un circuit électrique — comportement global",
      branch: "physique",
      durationMin: 18,
      youtubeId: "-DipSn_JE_g",
      videoTitle: "Transfert d’énergie dans un circuit électrique — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "P = U I = R I² = U²/R pour un dipôle ohmique.",
        "Énergie : E = P Δt (joule) ; 1 kWh = 3,6×10⁶ J.",
        "Générateur : fournit de l’énergie. Récepteur : la consomme (Joule, mécanique…).",
        "Bilan : énergie fournie = énergie utile + pertes.",
      ],
      conclusion:
        "Un circuit convertit de l’énergie : chimique → électrique → thermique / lumière / mouvement. La loi de Joule Q = R I² Δt explique l’échauffement des fils. Le rendement η = E_utile / E_fournie < 1. Piège : oublier de convertir les heures en secondes, ou confondre U aux bornes du générateur et U aux bornes de R. En SM, on combine souvent U=E−rI (générateur réel) avec un bilan d’énergie. Lis bien ce qui est « utile » (chaleur dans une résistance de chauffage, ou travail mécanique d’un moteur).",
      formula: "P = U I    ;    E = P t",
    },
    {
      id: "champ-magnetique",
      subject: "pc",
      semester: 2,
      chapter: "Le champ magnétique",
      branch: "physique",
      durationMin: 16,
      youtubeId: "jgpgnwYzOF8",
      videoTitle: "Champ magnétique — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "B⃗ : grandeur vectorielle, unité tesla (T).",
        "Lignes de champ fermées : sortent du N, entrent par le S d’un aimant.",
        "Terre : boussole = petit aimant ; pôle nord de l’aiguille vers le nord géographique.",
        "Spectre magnétique : limaille de fer.",
      ],
      conclusion:
        "Le champ magnétique se visualise par des lignes fermées (pas de « charges magnétiques » isolées). Un aimant a toujours deux pôles. La boussole s’aligne sur B⃗. Piège : croire que le pôle nord géographique est un pôle nord magnétique (c’est un sud magnétique). En SM, ce chapitre est surtout qualitatif avant « B créé par un courant ». Retiens : direction, sens, spectre, et que B est plus intense où les lignes sont serrées. Teslas : le champ terrestre est ~ 4×10⁻⁵ T, un aimant de TP quelques mT à 0,1 T.",
      formula: "Unité de B : tesla (T)    ;    1 G = 10⁻⁴ T",
    },
    {
      id: "champ-magnetique-courant",
      subject: "pc",
      semester: 2,
      chapter: "Le champ magnétique créé par un courant électrique",
      branch: "physique",
      durationMin: 18,
      youtubeId: "ncb0rSgenr8",
      videoTitle: "Champ magnétique créé par un courant électrique — 1 Bac",
      channel: "TOP PHYSIQUE CHIMIE",
      basics: [
        "Fil droit : lignes = cercles, sens par la règle de la main droite.",
        "Spire / bobine / solénoïde : B ≈ μ0 n I à l’intérieur (solénoïde long).",
        "B proportionnel à I.",
        "μ0 = 4π × 10⁻⁷ SI.",
      ],
      conclusion:
        "Un courant crée un champ magnétique. Pour le fil, les lignes sont des cercles ; pour le solénoïde, B est quasi uniforme à l’intérieur, faible à l’extérieur. Augmenter n (spires par mètre) ou I augmente B. Piège : sens de B inversé (règle de la main), ou appliquer B=μ0 n I à une simple spire. En SM, on te demande souvent de comparer aimant et bobine (même spectre). Prépare les schémas : croix / points pour le courant, et les flèches de B.",
      formula: "Solénoïde : B = μ_0 n I",
    },
    {
      id: "laplace",
      subject: "pc",
      semester: 2,
      chapter: "Les forces électromagnétiques — loi de Laplace",
      branch: "physique",
      durationMin: 18,
      youtubeId: "VO2gQclGVIQ",
      videoTitle: "La force de Laplace — résumé et exercices",
      channel: "Prof Ridouan",
      basics: [
        "Force de Laplace : F⃗ = I ℓ⃗ ∧ B⃗ , F = I ℓ B sin α.",
        "ℓ⃗ : sens du courant, longueur dans B.",
        "Direction ⊥ au plan (I, B). Sens : règle des trois doigts.",
        "Rail de Laplace : un conducteur peut se mettre en mouvement.",
      ],
      conclusion:
        "Laplace, c’est « le courant dans un champ B subit une force ». Maximum si I ⊥ B (sin 90°=1), nulle si I parallèle à B. Le rail de Laplace est l’exercice type : F = I ℓ B, parfois équilibrée par le poids ou un frottement. Piège : mauvais angle α, ou oublier que F est perpendiculaire à I et à B. En SM, relie ce chapitre à l’énergie : le travail de Laplace peut faire bouger une barre (moteur électrique élémentaire). Dessine toujours I, B, F avant de calculer.",
      formula: "F = I ℓ B sin α",
    },
    {
      id: "visibilite-objet",
      subject: "pc",
      semester: 2,
      chapter: "Visibilité d’un objet",
      branch: "physique",
      durationMin: 12,
      youtubeId: "IX-u13Yh2Xw",
      videoTitle: "Visibilité d’un objet — optique 1er Bac",
      channel: "Prof Ridouan",
      basics: [
        "Pour voir un objet : lumière + œil + chemin optique jusqu’à l’œil.",
        "Objet lumineux (source) vs éclairé (diffuse).",
        "Milieu transparent ; obstacle opaque → ombre.",
        "Faisceau, rayon, propagation rectiligne dans un milieu homogène.",
      ],
      conclusion:
        "Chapitre court et visuel : on voit un objet si des rayons issus de cet objet (émis ou diffusés) atteignent l’œil. Un objet dans le noir n’est pas visible sans éclairage. La propagation rectiligne explique ombres et éclipses. Piège : croire qu’il faut forcément une lentille pour « voir ». En SM, c’est l’introduction à l’optique géométrique (miroirs, lentilles). Retiens le vocabulaire : source, diffuseur, faisceau incident / réfléchi / transmis, et le schéma du rayon qui entre dans l’œil.",
      formula: "Propagation rectiligne de la lumière (milieu homogène)",
    },
    {
      id: "miroir-plan",
      subject: "pc",
      semester: 2,
      chapter: "Les images formées par un miroir plan",
      branch: "physique",
      durationMin: 14,
      youtubeId: "VVj51bJp7bM",
      videoTitle: "Image d’un objet par un miroir plan",
      channel: "MOMA SCHOOL",
      basics: [
        "i = i' (angle d’incidence = angle de réflexion).",
        "Image virtuelle, symétrique de l’objet par rapport au miroir.",
        "Même taille, même sens (droite), distance objet = distance image.",
        "On ne peut pas la recevoir sur un écran.",
      ],
      conclusion:
        "Le miroir plan donne toujours une image virtuelle, droite, de même taille, située « derrière » le miroir par symétrie. Pour construire : deux rayons, dont les prolongements se coupent. Piège : tracer l’image réelle, ou se tromper sur la symétrie (distance). En SM, les exercices portent sur la position d’un objet vu dans une glace, un champ visuel, ou un système de deux miroirs. Rédige : « par construction, H' est le symétrique de H ».",
      formula: "i = i'    ;    AH = AH' (symétrie)",
    },
    {
      id: "lentille-convergente",
      subject: "pc",
      semester: 2,
      chapter: "Les images formées par une lentille mince convergente",
      branch: "physique",
      durationMin: 20,
      youtubeId: "UZlb2smRk7w",
      videoTitle: "Les lentilles minces",
      channel: "ESSAID Physique chimie",
      basics: [
        "Foyer image F' : rayons // à l’axe émergent par F'. Distance focale f' = OF'.",
        "Trois rayons particuliers pour construire l’image.",
        "Relation de Descartes : 1/f' = 1/OA' − 1/OA (algébrique, origin O).",
        "Grandissement γ = OA'/OA = A'B'/AB.",
      ],
      conclusion:
        "Selon la position de l’objet (avant F, entre F et O…), l’image est réelle ou virtuelle, plus grande ou plus petite, droite ou renversée. C’est le cœur de l’optique 1er Bac. Respecte la convention de signes de ton manuel (souvent Descartes). Piège : mélanger f et f', ou oublier que OA est négatif pour un objet réel à gauche. Applications : œil, loupe, projecteur, appareil photo. En SM, un exercice complet = construction + calcul + nature de l’image.",
      formula: "1/f' = 1/OA' − 1/OA",
    },

    /* ——— PC CHIMIE S2 ——— */
    {
      id: "expansion-organo",
      subject: "pc",
      semester: 2,
      chapter: "Expansion de la chimie organique",
      branch: "chimie",
      durationMin: 14,
      youtubeId: "ovGwDGBJ8NE",
      videoTitle: "Expansion de la chimie organique — 1 Bac",
      channel: "Prof Ridouan",
      basics: [
        "Chimie organique : composés du carbone (sauf CO₂, carbonates, etc. selon le poly MEN).",
        "Carbone tétravalent : 4 liaisons, chaînes et cycles possibles.",
        "Sources : pétrole, gaz, charbon, biomasse ; raffinage et craquage.",
        "Enjeux : médicaments, polymères, carburants, pollution, chimie verte.",
      ],
      conclusion:
        "La chimie organique étudie les composés centrés sur le carbone, atome tétravalent capable d’enchaîner des liaisons C–C : d’où la diversité des molécules du vivant et de l’industrie. Elle s’est étendue à la synthèse à partir du pétrole et du gaz (raffinage, craquage). On y rattache plastiques, médicaments, carburants — et les problèmes de ressources fossiles. Piège : tout composé contenant du carbone n’est pas « organique » au sens scolaire (CO₂, HCO₃⁻, carbonates restent du côté minéral). Ce chapitre ouvre le S2 : ensuite on classera les molécules par squelette carboné, puis par groupes caractéristiques.",
      formula: "Le carbone est tétravalent (4 liaisons)",
    },
    {
      id: "squelettes-carbones",
      subject: "pc",
      semester: 2,
      chapter: "Les molécules organiques et les squelettes carbonés",
      branch: "chimie",
      durationMin: 18,
      youtubeId: "592tLsY7aRU",
      videoTitle: "Squelette carboné des molécules organiques — 1 Bac",
      channel: "Prof Ridouan",
      basics: [
        "Formules : brute, développée, semi-développée, topologique.",
        "Alcane C_nH_{2n+2} ; alcène C_nH_{2n} ; cycloalcane C_nH_{2n}.",
        "Isomérie de chaîne et de position ; Z/E des alcènes si au programme.",
        "Nomenclature : chaîne la plus longue + locants (méthyl, éthyl…).",
      ],
      conclusion:
        "On représente une molécule par plusieurs formules : brute, semi-développée, topologique (sommets = C). Le squelette saturé acyclique est un alcane C_nH_{2n+2} ; une double liaison donne un alcène. La chaîne principale est la plus longue, pas la plus « droite » sur le dessin. Même formule brute + squelettes différents = isomères de chaîne (butane / méthylpropane). Pièges : oublier les H en topologique ; mal numéroter. La double liaison est plane : d’où d’éventuels stéréoisomères Z/E. Sans formule juste, les réactions du chapitre suivant sont illisibles.",
      formula: "Alcane (linéaire) : C_n H_{2n+2}",
    },
    {
      id: "modification-squelette",
      subject: "pc",
      semester: 2,
      chapter: "Modification du squelette carboné",
      branch: "chimie",
      durationMin: 16,
      youtubeId: "4Ne0CBSt4F4",
      videoTitle: "Modification des squelettes carbonés",
      channel: "Rabia bayad",
      basics: [
        "Craquage : rupture de C–C à chaud (alcane long → alcane court + alcène).",
        "Réformage : isomérisation (linéaire → ramifié) et cyclisation.",
        "Addition sur C=C : H₂, X₂, HX, H₂O (acide) — Markovnikov si alcène dissymétrique.",
        "Polymérisation : n H₂C=CH₂ → polyéthylène.",
      ],
      conclusion:
        "Modifier le squelette, c’est casser ou créer des liaisons C–C, ou transformer une insaturation. Le craquage fournit des fragments plus courts dont un alcène. Sur C=C, l’addition est la réaction-type : H₂ (Ni/Pt) sature ; H₂O en milieu acide donne un alcool ; HX un halogénoalcane. Markovnikov : H va sur le carbone déjà le plus hydrogéné. Pièges : craquage qui ne conserve pas les atomes ; Markovnikov inversé ; confondre addition et substitution. En devoir SM, on donne souvent un alcène et on demande hydratation, hydrogénation, ou l’équation de craquage.",
      formula: "n H2C=CH2 → —[CH2−CH2]_n—  (polymérisation)",
    },
    {
      id: "groupes-caracteristiques-alcools",
      subject: "pc",
      semester: 2,
      chapter: "Les groupes caractéristiques — réactivité des alcools",
      branch: "chimie",
      durationMin: 20,
      youtubeId: "TqTTfROpSyo",
      videoTitle: "Rappel sur les alcools — chimie organique 1 Bac / 2 Bac BIOF",
      channel: "Prof Brahim Noureddine PC",
      basics: [
        "Groupe hydroxyle –OH : alcool R–OH, classe I / II / III.",
        "Nomenclature : …ol, locant le plus petit (éthanol, propan-2-ol).",
        "Oxydation ménagée : I → aldéhyde puis acide ; II → cétone ; III : pas d’oxydation ménagée.",
        "Déshydratation (H₂SO₄, chauffage) → alcène + H₂O. Tests : DNPH, Fehling / Tollens.",
      ],
      conclusion:
        "On classe l’alcool en primaire, secondaire ou tertiaire selon le nombre de C liés au carbone porteur de OH : l’oxydation en dépend. Un I s’oxyde en aldéhyde puis en acide (oxydant en excès) ; un II en cétone ; un III ne s’oxyde pas de façon ménagée. La déshydratation acide à chaud donne un alcène (Zaïtsev : souvent l’alcène le plus substitué). Pièges : confondre alcool et phénol ; oxyder un III ; aldéhyde vs cétone au test de Fehling (la cétone ne réduit pas). Exercice type : isomères de C₃H₈O, leur classe, produit d’oxydation, équation de déshydratation.",
      formula: "R−CH2OH  —[ox]→  R−CHO  —[ox]→  R−COOH",
    },
  ],
};
